apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: kgf-dev
  name: storage-oss-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: ""
  selector:
    matchLabels:
      alicloud-pvname: oss-storage-pv